In [1]:
from datetime import datetime
import os

modelType = 'dilated3DNetForNii'

logFileDir = os.path.join('../logging', modelType)
if not os.path.exists(logFileDir):
    os.mkdir(logFileDir)
    
timeString = datetime.now().strftime('%y-%m-%d_%H:%M:%S')
logFileName = timeString + '{}.log'.format(modelType)
logFileName = os.path.join(logFileDir, logFileName)

print logFileName

import logging
logging.basicConfig(filename = logFileName, 
                    filemode='w', 
                    format = '%(name)s %(lineno)d %(levelname)s:%(message)s', 
                    level = logging.INFO)
logger = logging.getLogger('Jupyter Notebook')

../logging/dilated3DNetForNii/17-07-13_09:33:44dilated3DNetForNii.log


In [2]:
import utils.general as ge
reload(ge)
import utils.createROIMaskForNii as crn
reload(crn)
import utils.sampling as sp
reload(sp)
# import models.baseNet as bn
# reload(bn)
# from models.Layers import DilatedConv3DLayer
import generateTrainTestNetworkForNiiData as gtt

import time
import theano
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook

%matplotlib inline 

/home/mountain/anaconda3/envs/biomediclasagne/lib/python2.7/site-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 6020 on context None
Mapped name None to device cuda0: GeForce GTX 750 Ti (0000:01:00.0)


In [3]:
reload(gtt)

<module 'generateTrainTestNetworkForNiiData' from 'generateTrainTestNetworkForNiiData.pyc'>

In [4]:
configFile = '/home/mountain/Desktop/BrainNets/code/configs/{}.cfg'.format(modelType)

In [5]:
configFile

'/home/mountain/Desktop/BrainNets/code/configs/dilated3DNetForNii.cfg'

In [6]:
baseNet = gtt.generateNetwork(configFile)

Shape.0 Subtensor{int64}.0


In [7]:
gtt.trainNetwork(baseNet, configFile)

Shape.0 Subtensor{int64}.0


KeyboardInterrupt: 

In [13]:
gtt.testNetwork(baseNet, configFile)

Shape.0 Subtensor{int64}.0


In [11]:
os.path.join('/abc', 'ds')

'/abc/ds'

In [ ]:
dataPath = '/home/mountain/Desktop/BrainNets/data/BRATS2015_Training'

In [ ]:
dataPath = '/home/mountain/Desktop/BrainNets/data/SimpleExploreSomeData'

In [ ]:
outputPath = '/home/mountain/Desktop/BrainNets/data/normTrainingDataWithROI'

In [ ]:
cr.normAndCreateROIForAllFiles(dataPath, outputPath)

In [97]:
import utils.createROIMaskForNii as crn
reload(crn)

<module 'utils.createROIMaskForNii' from 'utils/createROIMaskForNii.pyc'>

In [98]:
dataPath = '/home/mountain/Desktop/BrainNets/data/SimpleExploreSomeNiiData'

In [3]:
dataPath = '/home/mountain/Desktop/BrainNets/data/Brats17TrainingData'

In [4]:
outputPath = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI'

In [5]:
crn.normAndCreateROIForAllFiles(dataPath, outputPath)

In [ ]:
testDataPath  ='/home/mountain/Desktop/BrainNets/data/Testing'

In [ ]:
testDataOutputPath = '/home/mountain/Desktop/BrainNets/data/normTestDataWithROI'

In [ ]:
cr.normAndCreateROIForAllFiles(testDataPath, testDataOutputPath, True)

In [ ]:
a = []

In [ ]:
a[2:3]

In [ ]:
a[0]

In [33]:
import utils.loadNiiData as lni
reload(lni)

<module 'utils.loadNiiData' from 'utils/loadNiiData.py'>

In [34]:
patientDir = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI/HGG/Brats17_2013_13_1'

In [35]:
arrays = lni.loadSinglePatientData(patientDir)

In [36]:
image = arrays[0]

In [37]:
image.shape

(4, 240, 240, 155)

In [58]:
import utils.sampleNii as sni
reload(sni)

<module 'utils.sampleNii' from 'utils/sampleNii.py'>

In [50]:
samples = sni.sampleWholeBrain(patientDir, 
                               'normImage', 
                               ['t1ce', 't1', 't2', 'flair'], 
                               [17, 17, 17], 
                               15,
                               False, 
                               True)

In [51]:
len(samples)

5

In [52]:
len(samples[0])

94202

In [53]:
samples[-1]

[]

In [54]:
del samples

In [55]:
patientsDirList = []

In [56]:
patientsDirList.append(patientDir)

In [60]:
samples = sni.getSamplesForSubEpoch(100,
                          patientsDirList,
                          useROI = True,
                          modals = ['t1ce', 't1', 't2', 'flair'],
                          normType = 'normImage',
                          trainSampleSize = [25, 25, 25],
                          receptiveField = 17,
                          weightMapType = 0,
                          parallel = False)

In [62]:
len(samples[0])

100

In [64]:
samples[0][0].shape

(4, 25, 25, 25)

In [25]:
import nibabel as nib
import numpy as np

In [26]:
seg = '/home/mountain/Desktop/BrainNets/data/Brats17TrainingData/HGG/Brats17_2013_7_1/Brats17_2013_7_1_seg.nii.gz'

In [46]:
tice = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI/HGG/Brats17_2013_13_1/normBrainBrats17_2013_13_1_t1ce.nii.gz'

In [55]:
tice = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI/HGG/Brats17_2013_13_1/normImageBrats17_2013_13_1_t1ce.nii.gz'

In [64]:
roi = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI/HGG/Brats17_2013_13_1/Brats17_2013_13_1.ROI.nii.gz'

In [101]:
new = '/home/mountain/Desktop/BrainNets/data/normNiiTrainingDataWithROI/HGG/Brats17_2013_19_1/normImageBrats17_2013_19_1_flair.nii.gz'

In [102]:
image = nib.load(new)

In [103]:
array = image.get_data()

In [74]:
ROIBoolArray = array > 0
ROIArray = ROIBoolArray.astype('int16')

In [76]:
ROIArray.dtype

dtype('int16')

In [77]:
ROIImage = nib.Nifti1Image(ROIArray, image.affine)

In [104]:
array[1,2,3]

-0.41492873

In [78]:
ar = ROIImage.get_data()

In [79]:
ar.dtype

dtype('int16')

In [85]:
patientName = '/home/mountain/Desktop/'
# Name the ROI file
ROIFileName = patientName + 'ROI.nii'
nib.save(ROIImage, ROIFileName)

In [86]:
reLoadImage = '/home/mountain/Desktop/ROI.nii'

In [87]:
reimage = nib.load(reLoadImage)

In [88]:
reArray = reimage.get_data()

In [89]:
reArray.dtype

dtype('<i2')

In [106]:
array

array([[[-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        ..., 
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873]],

       [[-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        [-0.41492873, -0.41492873, -0.41492873, ..., -0.41492873,
         -0.41492873, -0.41492873],
        ..., 
        [-0.41492873, -0.41492873, -0.41492873, ...,

In [107]:
b = array.astype('float32')

In [108]:
b == array

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True, 

In [105]:
array.dtype

dtype('<f4')

In [70]:
def numpyArrayCounter(numpyArray):

    unique, counts = np.unique(numpyArray, return_counts = True)

    return np.asarray((unique, counts)).T

In [71]:
count = numpyArrayCounter(array)

In [73]:
count

array([[      0, 7356322],
       [      1, 1571678]])